# The `site.yml` blueprint defines the look of the start page (Dashboard) of the Panel.

# The site blueprint usually provides easy access to all main pages of the site.
# In this example blueprint, we also show subpages of the `photography` and `notes` pages.
# More about the site blueprint: https://getkirby.com/docs/reference/panel/blueprints/site

# The layout of this form has two columns:
columns:
  - width: 1
    sections:
      logo:
        type: fields
        fields:
          logo_image:
            label: Logo
            type: files
            multiple: false
            layout: cards
            image:
              cover: true
            uploads:
              template: image
          appointment_label:
            label: Bouton header – Libellé
            type: text
            width: 1/2
            default: PRENDRE RENDEZ-VOUS
          appointment_url:
            label: Bouton header – Lien
            type: url
            width: 1/2

  # The second column has two sections, `notes` and `pages`
  - width: 1
    sections:
      # The `pages` pages section shows other main pages of the site
      # Using the `templates` option, we limit which types of pages are shown
      # Using the `create` option, we limit the type of page that can be created when a new page is created
      # Note that the `sandbox` page and the `error` page that also exist in the content folder but use different blueprints thus do not show up in the list
      # Since the error page's blueprint is set to `read: false`, it wouldn't show up here even if you added the error blueprint to the templates list
      pages:
        type: pages
        create: default
        templates:
          - about
          - home
          - offers
          - nos-realisations
          - blog
          - default

      offers_children:
        type: pages
        label: Offres
        parent: site.find("nos-offres")
        templates:
          - product-starter
          - ai-developpement
          - prestation-sur-mesure
        create:
          - product-starter
          - ai-developpement
          - prestation-sur-mesure

      realisations_children:
        type: pages
        label: Réalisations
        parent: site.find("nos-realisations")
        templates:
          - realisation
        create:
          - realisation

      blog_children:
        type: pages
        label: Articles de Blog
        parent: site.find("le-blog")
        templates:
          - article
        create:
          - article
        sortable: true
        status: all
        info: "{{ page.date.toDate('d/m/Y') }} - {{ page.views }} vues"
        layout: list
        size: medium
        image:
          cover: true
          ratio: 3/2

      footer:
        extends: sections/footer
